### ISSUE TITLE
Request - make watermark printable 

### ISSUE THREAD

**Issue by dorsegalx** [Pewww/react-awesome-watermark#1]
When you print the page mater mark becomes a white layer on top of the .inner-watermark CSS class.

Any ideas on how to make it printable?

<img width="1140" alt="Screen Shot 2022-01-14 at 16 48 47" src="https://user-images.githubusercontent.com/80476373/149534930-499dca5d-cf25-4321-8343-39eb545f7570.png">

**Comment by Pewww** [comment]
Hi @dorsegalx ! I think you can solve that problem if you add this css property inside body(or another target).
```
body {
  -webkit-print-color-adjust: exact;
}
```

<img src="https://user-images.githubusercontent.com/23455736/149613130-11d8fe6d-5c44-4de8-8186-14b4aaf68c77.png" width="400">


Reference: https://stackoverflow.com/questions/6670151/how-can-i-force-browsers-to-print-background-images-in-css

**Comment by Pewww** [comment]
It it was helpful, please close the issue :D
