### ISSUE TITLE
Add zIndex option in WatermarkStyle interface

### ISSUE THREAD

**Issue by rrxs** [Pewww/react-awesome-watermark#4]
Hello friend, i'd like to set a custom zIndex option, I'm having some trouble with modals and etc...

**Comment by Pewww** [comment]
Hello @rrxs Thanks for using this package!
How about giving 'className' option to watermark like this?
If this doesn't work, please re-comment 🙏

```
<Watermark className="custom-watermark" />

// in css or styled-components..etc
.custom-watermark {
  z-index: {value};
}
```
