### ISSUE TITLE
How we can make different spacing by vertical and horizontal?

### ISSUE THREAD

**Issue by ormus2002** [Pewww/react-awesome-watermark#5]
Hello!
I am using "multiple" option, and want make space between strings.
Now we have "space" option, but looks it same size for vertical and horizontal (horizontal space calculated between of 1st letter in "text" sentence). Could you add please new option for horizontal spacing? (for multiple case, when sentence is long, it would be useful)

**Comment by Pewww** [comment]
Thanks for issuing!
I will handle it asap.

**Comment by Pewww** [comment]
@ormus2002 Sorry for being late 😢 
Fixed in v1.0.5
