### ISSUE TITLE
Error typescript

### ISSUE THREAD

**Issue by anonymousid24111** [Pewww/react-awesome-watermark#6]
I got an error as below:
![image](https://user-images.githubusercontent.com/44476134/227879292-8634b40d-f1b8-4562-8eb7-aab2443a2b84.png)

(alias) const Watermark: React.FC<WatermarkProps>
import Watermark
Type '{ children: null; text: string; style: { width: number; height: number; opacity: number; }; multiple: true; }' is not assignable to type 'IntrinsicAttributes & WatermarkProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & WatermarkProps'.ts(2322)

And I tried adding a 'children' property to WatermarkProps interface. It works.
![image](https://user-images.githubusercontent.com/44476134/227878773-4225ba01-0f98-498a-9a0e-d527af9ba7d1.png)

**Comment by Pewww** [comment]
Hi @anonymousid24111 Are you using react v18?

**Comment by anonymousid24111** [comment]
> Hi @anonymousid24111 Are you using react v18?

yes, I'm using react v18.2.0

**Comment by Pewww** [comment]
> > Hi @anonymousid24111 Are you using react v18?
> 
> yes, I'm using react v18.2.0

In react v18, they don't provide 'children' type in React.FC more.
ref: https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc

I will handle it asap.
Thank you :D

**Comment by Pewww** [comment]
@anonymousid24111 Sorry for being late 😢 
Fixed in v1.0.5
